### ISSUE TITLE
No clue how to compile this correctly to work for both simulator and device

### ISSUE THREAD

**Issue by Delimiters** [nhgrif/SQLConnect#2]
So I've tried to compile a fat file using:
lipo -create ${CURRENTPATH}/build/${LIB}/i386/lib/libsybdb.a ${CURRENTPATH}/build/${LIB}/armv7/lib/libsybdb.a ${CURRENTPATH}/build/${LIB}/armv7s/lib/libsybdb.a ${CURRENTPATH}/build/${LIB}/arm64/lib/libsybdb.a ${CURRENTPATH}/build/${LIB}/x86_64/lib/libsybdb.a -output ${CURRENTPATH}/build/${LIB}/Fat/lib/libsybdb.a
after compiling freetds for all of those architectures. 
This ends up making a fat binary file that works for devices but fails on simulators.  Any idea what I'm doing wrong?

**Comment by Delimiters** [comment]
I'd like to add that the reason I'm trying to recompile the freetds binary is because the binary uploaded here is not compatible with ipv6.  After recompiling with a newer freetds version it is compatible with ipv6, but as I said it does not work on the simulator.

**Comment by nhgrif** [comment]
I'm pretty busy for the next two weeks, but I can try to look at this after that.

If I get it figured out, I'll leave a comment explaining what I did to get it working as well as update the repo with the new binary.  Otherwise, if you get it working in the meantime, can you make a PR with the working binary?

**Comment by Delimiters** [comment]
I actually found a working binary from the project you were inspired by, SQLClient.  I didn't see anywhere where he explained how he compiled from but if you look at his page he has the precompiled binary with the most recent version of freetds.  Thanks for responding, though.  Also this is Jake, I'm the one working on 585 mobile now lol.
